### ISSUE TITLE
Waiting on DB after upgrade to 3.5.0 due SECRET_KEY length

### ISSUE THREAD

**Issue by mburgholte** [netbox-community/netbox-docker#1003]
### Current Behavior

Hi there!
After the upgrade to 3.5.0, my Netbox unfortunately no longer starts. The start-up is stuck at "Waiting on DB". The SECRET_KEY stored in the netbox.env has a length of 51 characters.

`cat env/netbox.env | grep SECRET_KEY | sed -e 's/SECRET_KEY=//g' | wc -c`
`51`

The original SECRET_KEY from the git repo includes the following count. 

`cat env/netbox.env | grep SECRET_KEY | sed -e 's/SECRET_KEY=//g' | wc -c`
`61`

With the longer key, the Netbox instance starts.

The script "generate_secret_key.py" also only delivers a key of 51 characters.
`docker compose exec netbox /opt/netbox/netbox/generate_secret_key.py | wc -c`
`51`

### Expected Behavior

The tool "generate_secret_key.py" should provide the correct count. Potentially, in my case, the documentation does not fit. It is written that "A minimum length of 50 characters is now enforced for the SECRET_KEY configuration parameter." I'm just over that. I have been able to recreate this behaviour on two different systems. 
Maybe I just missed something. Thanks for this nice piece of software.

### Docker Compose Version

Docker Compose version v2.17.3

### Docker Version

```text
Client: Docker Engine - Community
 Version:           23.0.5
 API version:       1.42
 Go version:        go1.19.8
 Git commit:        bc4487a
 Built:             Wed Apr 26 16:21:07 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.5
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.8
  Git commit:       94d3ad6
  Built:            Wed Apr 26 16:21:07 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.20
  GitCommit:        2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc:
  Version:          1.1.5
  GitCommit:        v1.1.5-0-gf19387a
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### The git Revision

22486fefb5c4cc326bd091abeac5314eb7acd37f

### The git Status

```text
On branch release
Your branch is up to date with 'origin/release'.
```

### Startup Command

docker compose up

### NetBox Logs

```text
docker compose up
[+] Running 6/0
 ✔ Container netbox-docker-redis-cache-1          Created                                                                                                                                                      0.0s
 ✔ Container netbox-docker-postgres-1             Created                                                                                                                                                      0.0s
 ✔ Container netbox-docker-redis-1                Created                                                                                                                                                      0.0s
 ✔ Container netbox-docker-netbox-1               Recreated                                                                                                                                                    0.0s
 ✔ Container netbox-docker-netbox-worker-1        Recreated                                                                                                                                                    0.0s
 ✔ Container netbox-docker-netbox-housekeeping-1  Recreated                                                                                                                                                    0.1s
Attaching to netbox-docker-netbox-1, netbox-docker-netbox-housekeeping-1, netbox-docker-netbox-worker-1, netbox-docker-postgres-1, netbox-docker-redis-1, netbox-docker-redis-cache-1
netbox-docker-redis-cache-1          | 1:C 03 May 2023 08:50:28.802 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
netbox-docker-redis-cache-1          | 1:C 03 May 2023 08:50:28.802 # Redis version=7.0.11, bits=64, commit=00000000, modified=0, pid=1, just started
netbox-docker-redis-cache-1          | 1:C 03 May 2023 08:50:28.802 # Configuration loaded
netbox-docker-redis-cache-1          | 1:M 03 May 2023 08:50:28.802 * monotonic clock: POSIX clock_gettime
netbox-docker-redis-cache-1          | 1:M 03 May 2023 08:50:28.803 * Running mode=standalone, port=6379.
netbox-docker-redis-cache-1          | 1:M 03 May 2023 08:50:28.803 # Server initialized
netbox-docker-redis-cache-1          | 1:M 03 May 2023 08:50:28.804 * Loading RDB produced by version 7.0.11
netbox-docker-redis-cache-1          | 1:M 03 May 2023 08:50:28.804 * RDB age 458 seconds
netbox-docker-redis-cache-1          | 1:M 03 May 2023 08:50:28.804 * RDB memory usage when created 0.82 Mb
netbox-docker-redis-cache-1          | 1:M 03 May 2023 08:50:28.804 * Done loading RDB, keys loaded: 0, keys expired: 0.
netbox-docker-redis-cache-1          | 1:M 03 May 2023 08:50:28.804 * DB loaded from disk: 0.000 seconds
netbox-docker-redis-cache-1          | 1:M 03 May 2023 08:50:28.804 * Ready to accept connections
netbox-docker-redis-1                | 1:C 03 May 2023 08:50:28.905 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
netbox-docker-redis-1                | 1:C 03 May 2023 08:50:28.905 # Redis version=7.0.11, bits=64, commit=00000000, modified=0, pid=1, just started
netbox-docker-redis-1                | 1:C 03 May 2023 08:50:28.905 # Configuration loaded
netbox-docker-redis-1                | 1:M 03 May 2023 08:50:28.905 * monotonic clock: POSIX clock_gettime
netbox-docker-redis-1                | 1:M 03 May 2023 08:50:28.906 * Running mode=standalone, port=6379.
netbox-docker-redis-1                | 1:M 03 May 2023 08:50:28.906 # Server initialized
netbox-docker-redis-1                | 1:M 03 May 2023 08:50:28.907 * Reading RDB base file on AOF loading...
netbox-docker-redis-1                | 1:M 03 May 2023 08:50:28.907 * Loading RDB produced by version 7.0.11
netbox-docker-redis-1                | 1:M 03 May 2023 08:50:28.907 * RDB age 3191 seconds
netbox-docker-redis-1                | 1:M 03 May 2023 08:50:28.907 * RDB memory usage when created 0.82 Mb
netbox-docker-redis-1                | 1:M 03 May 2023 08:50:28.907 * RDB is base AOF
netbox-docker-redis-1                | 1:M 03 May 2023 08:50:28.907 * Done loading RDB, keys loaded: 0, keys expired: 0.
netbox-docker-redis-1                | 1:M 03 May 2023 08:50:28.907 * DB loaded from base file appendonly.aof.1.base.rdb: 0.000 seconds
netbox-docker-redis-1                | 1:M 03 May 2023 08:50:28.921 * DB loaded from incr file appendonly.aof.1.incr.aof: 0.014 seconds
netbox-docker-redis-1                | 1:M 03 May 2023 08:50:28.921 * DB loaded from append only file: 0.014 seconds
netbox-docker-redis-1                | 1:M 03 May 2023 08:50:28.922 * Opening AOF incr file appendonly.aof.1.incr.aof on server start
netbox-docker-redis-1                | 1:M 03 May 2023 08:50:28.922 * Ready to accept connections
netbox-docker-postgres-1             |
netbox-docker-postgres-1             | PostgreSQL Database directory appears to contain a database; Skipping initialization
netbox-docker-postgres-1             |
netbox-docker-postgres-1             | 2023-05-03 08:50:29.049 UTC [1] LOG:  starting PostgreSQL 15.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit
netbox-docker-postgres-1             | 2023-05-03 08:50:29.049 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
netbox-docker-postgres-1             | 2023-05-03 08:50:29.049 UTC [1] LOG:  listening on IPv6 address "::", port 5432
netbox-docker-postgres-1             | 2023-05-03 08:50:29.051 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
netbox-docker-postgres-1             | 2023-05-03 08:50:29.058 UTC [24] LOG:  database system was shut down at 2023-05-03 08:42:50 UTC
netbox-docker-postgres-1             | 2023-05-03 08:50:29.066 UTC [1] LOG:  database system is ready to accept connections
netbox-docker-netbox-1               | 🧬 loaded config '/etc/netbox/config/configuration.py'
netbox-docker-netbox-1               | 🧬 loaded config '/etc/netbox/config/extra.py'
netbox-docker-netbox-1               | 🧬 loaded config '/etc/netbox/config/logging.py'
netbox-docker-netbox-1               | 🧬 loaded config '/etc/netbox/config/plugins.py'
netbox-docker-netbox-1               | Traceback (most recent call last):
netbox-docker-netbox-1               |   File "/opt/netbox/netbox/./manage.py", line 10, in <module>
netbox-docker-netbox-1               |     execute_from_command_line(sys.argv)
netbox-docker-netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
netbox-docker-netbox-1               |     utility.execute()
netbox-docker-netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
netbox-docker-netbox-1               |     self.fetch_command(subcommand).run_from_argv(self.argv)
netbox-docker-netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/base.py", line 402, in run_from_argv
netbox-docker-netbox-1               |     self.execute(*args, **cmd_options)
netbox-docker-netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/base.py", line 443, in execute
netbox-docker-netbox-1               |     self.check()
netbox-docker-netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/base.py", line 475, in check
netbox-docker-netbox-1               |     all_issues = checks.run_checks(
netbox-docker-netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
netbox-docker-netbox-1               |     new_errors = check(app_configs=app_configs, databases=databases)
netbox-docker-netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/checks/templates.py", line 39, in check_string_if_invalid_is_string
netbox-docker-netbox-1               |     for conf in settings.TEMPLATES:
netbox-docker-netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/conf/__init__.py", line 92, in __getattr__
netbox-docker-netbox-1               |     self._setup(name)
netbox-docker-netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/conf/__init__.py", line 79, in _setup
netbox-docker-netbox-1               |     self._wrapped = Settings(settings_module)
netbox-docker-netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/conf/__init__.py", line 190, in __init__
netbox-docker-netbox-1               |     mod = importlib.import_module(self.SETTINGS_MODULE)
netbox-docker-netbox-1               |   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
netbox-docker-netbox-1               |     return _bootstrap._gcd_import(name[level:], package, level)
netbox-docker-netbox-1               |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
netbox-docker-netbox-1               |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
netbox-docker-netbox-1               |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
netbox-docker-netbox-1               |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
netbox-docker-netbox-1               |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
netbox-docker-netbox-1               |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
netbox-docker-netbox-1               |   File "/opt/netbox/netbox/netbox/settings.py", line 75, in <module>
netbox-docker-netbox-1               |     raise ImproperlyConfigured(
netbox-docker-netbox-1               | django.core.exceptions.ImproperlyConfigured: SECRET_KEY must be at least 50 characters in length. To generate a suitable key, run the following command:
netbox-docker-netbox-1               |   python /opt/netbox/netbox/generate_secret_key.py
netbox-docker-netbox-1               | ⏳ Waiting on DB... (0s / 30s)
```

### Content of docker-compose.override.yml

```yaml
version: '3.4'
services:
  netbox:
    ports:
      - 80:8080
```

**Comment by tobiasge** [comment]
The script `generate_secret_key.py` and the checks are implemented in Netbox directly, not in the Docker image.
Please open an issue in the Netbox repository.

**Comment by mburgholte** [comment]
Hi Tobias,
maybe it's a docker problem after all?

**Comment by tobiasge** [comment]
Hello,
I just tested it with the current release:
- `docker compose run netbox /opt/netbox/netbox/generate_secret_key.py`
- Pasted output into `env/netbox.env`
- `docker compose` up

It starts Netbox without an error.

**Comment by mburgholte** [comment]
Hi again!
Incredibly, that's exactly what I did yesterday without success. Repeated it today and it works. Please excuse the message.

**Comment by aravindh-murugesan** [comment]
I have the same problem and I tried to use the new generated key in the ENV file, and it did not work even after trying multiple times. So its definely worth checking out why?

Tried hardcoding the value in configuration.py and voila it works immediately.

**Comment by Delta1977** [comment]
> I have the same problem and I tried to use the new generated key in the ENV file, and it did not work even after trying multiple times. So its definely worth checking out why?
> 
> 
> 
> Tried hardcoding the value in configuration.py and voila it works immediately.
> 
> 
I had the same problem but I solved it: 

Did you use plugins and have a custom Dockerfile like Dockerfile-Plugins ? 

There must the secret_key be extended like this : 

RUN SECRET_KEY="dummydummydummydummydummydummydummydummydummydummy" /opt/netbox/venv/bin/python /opt/netbox/netbox/manage.py collectstatic --no-input

https://github.com/netbox-community/netbox-docker/wiki/Using-Netbox-Plugins#custom-docker-file

**Comment by kkthxbye-code** [comment]
generate_secret_key can return keys with # in, which ends the string in environment variables. Probably what is happening.

**Comment by mburgholte** [comment]
@kkthxbye-code Negative. Both secret_keys contain a hash sign.

**Comment by kkthxbye-code** [comment]
@mburgholte - Yeah, I was wrong, hashes need to be preceded by a space to count as a comment:

https://docs.docker.com/compose/environment-variables/env-file/

I still think the secret keys contain something that makes the string shorter. Parameter expansion would cause it. This key I generated with generate_secret_key.py will be shortened for example:

```SECRET_KEY=$mINUSD(QA3Zw^N2ezlyO@VUIGqEymTPDInDgXVW%tH%pcF5^q```

Output:

```
test_docker-ubuntu-1  | PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
test_docker-ubuntu-1  | HOSTNAME=45227aa4bd6a
test_docker-ubuntu-1  | SECRET_KEY=(QA3Zw^N2ezlyO@VUIGqEymTPDInDgXVW%tH%pcF5^q
test_docker-ubuntu-1  | HOME=/root
```

So `$mINUSD` is treated as an environment variable and is expanded to empty string.

Would have been a little easier if you posted a SECRET_KEY that fails though. Single quoting the key solves it:

`test_docker-ubuntu-1  | SECRET_KEY=$mINUSD(QA3Zw^N2ezlyO@VUIGqEymTPDInDgXVW%tH%pcF5^q`

**Comment by mburgholte** [comment]
I made a backup during my tests.

Not working:
`SECRET_KEY=r8OwDznj!!dci#P9ghmRfdu1Ysxm0AiPeDCQhKE+N_rClfWNj`

Working:
`SECRET_KEY=r(m)9nLGnz$(_q3N4z1k(EFsMCjjjzx08x9VhNVcfd%6RF#r!6DE@+V5Zk2X`

**Comment by kkthxbye-code** [comment]
@mburgholte - The not working one is 49 characters. Your own test:

```
➜  test_docker cat test.txt | grep SECRET_KEY | sed -e 's/SECRET_KEY=//g' | wc -c
50
```

50 - 1 newline = 49.

The one before you edited exhibits the issue I explained, where `$t0` is removed, making the string 47 characters long.

**Comment by mburgholte** [comment]
@kkthxbye-code lol that all makes sense. I am not sure if it was the right backup. The bottom line is that it works. Thanks for checking.
