### ISSUE TITLE
could not load library /usr/local/lib/postgresql/llvmjit.so

### ISSUE THREAD

**Issue by czephyr** [netbox-community/netbox-docker#1012]
### Current Behavior

postgres: `postgres-15alpine`
netbox: `netboxcommunity/netbox:v3.4.10-2.5.3`

On opening a changelong instance we incur into `OperationalError at /extras/changelog/3803728/`
```
<class 'django.db.utils.OperationalError'>

could not load library "/usr/local/lib/postgresql/llvmjit.so": Error relocating /usr/local/lib/postgresql/llvmjit.so: LLVMBuildGEP: symbol not found
```
Full traceback:
```
Environment:


Request Method: GET
Request URL: <fqdn>/extras/changelog/3803728/

Django Version: 4.1.8
Python Version: 3.10.6
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize',
 'corsheaders',
 'debug_toolbar',
 'graphiql_debug_toolbar',
 'django_filters',
 'django_tables2',
 'django_prometheus',
 'graphene_django',
 'mptt',
 'rest_framework',
 'social_django',
 'taggit',
 'timezone_field',
 'circuits',
 'dcim',
 'ipam',
 'extras',
 'tenancy',
 'users',
 'utilities',
 'virtualization',
 'wireless',
 'django_rq',
 'drf_yasg',
 'netbox_plugin_hardware_assignments.HardwareAssignmentsConfig',
 'netbox_qrcode.QRCodeConfig',
 'netbox_interface_sync.Config',
 'netbox_ipcalculator.IPCalcultorConfig',
 'netbox_initializers.NetBoxInitializersConfig',
 'netbox_topology_views.TopologyViewsConfig']
Installed Middleware:
['graphiql_debug_toolbar.middleware.DebugToolbarMiddleware',
 'django_prometheus.middleware.PrometheusBeforeMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'netbox.middleware.ExceptionHandlingMiddleware',
 'netbox.middleware.RemoteUserMiddleware',
 'netbox.middleware.LoginRequiredMiddleware',
 'netbox.middleware.DynamicConfigMiddleware',
 'netbox.middleware.APIVersionMiddleware',
 'netbox.middleware.ObjectChangeMiddleware',
 'django_prometheus.middleware.PrometheusAfterMiddleware']



Traceback (most recent call last):
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django_prometheus/db/common.py", line 71, in execute
    return super().execute(*args, **kwargs)

The above exception (could not load library "/usr/local/lib/postgresql/llvmjit.so": Error relocating /usr/local/lib/postgresql/llvmjit.so: LLVMBuildGEP: symbol not found
) was the direct cause of the following exception:
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/netbox/netbox/netbox/views/generic/base.py", line 26, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/opt/netbox/netbox/utilities/views.py", line 99, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/netbox/netbox/netbox/views/generic/object_views.py", line 73, in get
    **self.get_extra_context(request, instance),
  File "/opt/netbox/netbox/extras/views.py", line 508, in get_extra_context
    'related_changes_count': related_changes.count(),
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/models/query.py", line 621, in count
    return self.query.get_count(using=self.db)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 559, in get_count
    return obj.get_aggregation(using, ["__count"])["__count"]
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 544, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1398, in execute_sql
    cursor.execute(sql, params)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django_prometheus/db/common.py", line 71, in execute
    return super().execute(*args, **kwargs)

Exception Type: OperationalError at /extras/changelog/3803728/
Exception Value: could not load library "/usr/local/lib/postgresql/llvmjit.so": Error relocating /usr/local/lib/postgresql/llvmjit.so: LLVMBuildGEP: symbol not found
```

### Expected Behavior

Expected behavior would be to see the changelog instance page.

### Docker Compose Version

Docker Compose version 2.5.3

### Docker Version

```text
Client: Docker Engine - Community
 Version:           23.0.1
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        a5ee5b1
 Built:             Thu Feb  9 19:46:54 2023
 OS/Arch:           linux/amd64
 Context:           default
```

### The git Revision

doesnt apply because of ansible

### The git Status

```text
also doesnt apply because of ansible
```

### Startup Command

ansible docker_compose method

### NetBox Logs

```text
-05-12 10:52:48.007 UTC [364] STATEMENT:  SELECT COUNT(*) AS "__count" FROM "extras_objectchange" WHERE ("extras_objectchange"."request_id" = 'c57c8fca-8dc8-4816-9c4f-78e803afe562'::uuid AND NOT ("extras_objectchange"."id" = 3802797))
2023-05-12 10:55:28.655 UTC [22] LOG:  checkpoint starting: time
2023-05-12 10:55:28.921 UTC [22] LOG:  checkpoint complete: wrote 2 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.112 s, sync=0.068 s, total=0.266 s; sync files=4, longest=0.048 s, average=0.017 s; distance=10 kB, estimate=11779 kB
2023-05-12 11:00:29.021 UTC [22] LOG:  checkpoint starting: time
2023-05-12 11:00:33.986 UTC [22] LOG:  checkpoint complete: wrote 48 buffers (0.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=4.816 s, sync=0.035 s, total=4.965 s; sync files=4, longest=0.013 s, average=0.009 s; distance=200 kB, estimate=10621 kB
2023-05-12 11:04:38.936 UTC [408] ERROR:  could not load library "/usr/local/lib/postgresql/llvmjit.so": Error relocating /usr/local/lib/postgresql/llvmjit.so: LLVMBuildGEP: symbol not found
```

**Comment by tobiasge** [comment]
The logs you posted in the `Netbox Logs` section seem to show the original error in the Postgres container. I don't think this is fixable in the Netbox image.

**Comment by czephyr** [comment]
seems to be related to docker-library/postgres#1076

**Comment by tobiasge** [comment]
You can pin the version of the Postgres image in your `docker-compose.override.yml` to one that is not affected by this problem.
