### ISSUE TITLE
2.5.3 v3.4.10 ImportError: cannot import name 'use_connection' from 'rq'

### ISSUE THREAD

**Issue by FliesLikeABrick** [netbox-community/netbox-docker#1013]
### Current Behavior

Upon startup of NetBox 3.4.8 built with netbox-docker 2.5.3, a traceback is seen due to a failed import from rq

Based on issue 12415 in Netbox: https://github.com/netbox-community/netbox/issues/12415

This is a known issue with later versions of 3.4.x and 3.5.0 that may require pinning rq==1.13.0 because of the deprecation of 'use_connection' in rq.  3.5.1 fixes this because `use_connection` is fully removed from NetBox at this point.

We worked around this to build our 3.4.10 container by adding "rq==1.13.0" to requirements-container.txt

### Expected Behavior

The expectation is that NetBox runs successfully by avoiding use of later rq packages which do not contain the function(s) relied upon by NetBox (NetBox stops relying on these in 3.5.1+)

### Docker Compose Version

2.5.3

### Docker Version

```text
Client: Docker Engine - Community
 Version:           23.0.3
 API version:       1.42
 Go version:        go1.19.7
 Git commit:        3e7cbfd
 Built:             Tue Apr  4 22:04:18 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.3
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.7
  Git commit:       59118bf
  Built:            Tue Apr  4 22:02:01 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.20
  GitCommit:        2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc:
  Version:          1.1.5
  GitCommit:        v1.1.5-0-gf19387a
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### The git Revision

tag 2.5.3 (we have later commits in our internal repo)

### The git Status

```text
[rrawdon@mon101-dev cnvr-neteng-netbox-docker]$ git status
# On branch cnvr-dev
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#       modified:   requirements-container.txt
#
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#       env/cnvr-netbox.env
no changes added to commit (use "git add" and/or "git commit -a")
[rrawdon@mon101-dev cnvr-neteng-netbox-docker]$
```

### Startup Command

docker-compose up -d

### NetBox Logs

```text
cnvr-neteng-netbox-docker-redis-1                | 1:C 16 May 2023 19:21:30.329 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
cnvr-neteng-netbox-docker-redis-1                | 1:C 16 May 2023 19:21:30.329 # Redis version=7.0.10, bits=64, commit=00000000, modified=0, pid=1, just started
cnvr-neteng-netbox-docker-redis-1                | 1:C 16 May 2023 19:21:30.329 # Configuration loaded
cnvr-neteng-netbox-docker-redis-1                | 1:M 16 May 2023 19:21:30.329 * monotonic clock: POSIX clock_gettime
cnvr-neteng-netbox-docker-redis-1                | 1:M 16 May 2023 19:21:30.330 * Running mode=standalone, port=6379.
cnvr-neteng-netbox-docker-redis-1                | 1:M 16 May 2023 19:21:30.330 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
cnvr-neteng-netbox-docker-redis-1                | 1:M 16 May 2023 19:21:30.330 # Server initialized
cnvr-neteng-netbox-docker-redis-1                | 1:M 16 May 2023 19:21:30.330 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
cnvr-neteng-netbox-docker-redis-1                | 1:M 16 May 2023 19:21:30.352 * Reading RDB base file on AOF loading...
cnvr-neteng-netbox-docker-redis-1                | 1:M 16 May 2023 19:21:30.352 * Loading RDB produced by version 7.0.10
cnvr-neteng-netbox-docker-redis-1                | 1:M 16 May 2023 19:21:30.352 * RDB age 258433 seconds
cnvr-neteng-netbox-docker-redis-1                | 1:M 16 May 2023 19:21:30.352 * RDB memory usage when created 1.26 Mb
cnvr-neteng-netbox-docker-redis-1                | 1:M 16 May 2023 19:21:30.352 * RDB is base AOF
cnvr-neteng-netbox-docker-redis-1                | 1:M 16 May 2023 19:21:30.352 * Done loading RDB, keys loaded: 12, keys expired: 0.
cnvr-neteng-netbox-docker-redis-1                | 1:M 16 May 2023 19:21:30.352 * DB loaded from base file appendonly.aof.40.base.rdb: 0.001 seconds
cnvr-neteng-netbox-docker-redis-1                | 1:M 16 May 2023 19:21:33.048 * DB loaded from incr file appendonly.aof.40.incr.aof: 2.696 seconds
cnvr-neteng-netbox-docker-redis-1                | 1:M 16 May 2023 19:21:33.048 * DB loaded from append only file: 2.696 seconds
cnvr-neteng-netbox-docker-redis-1                | 1:M 16 May 2023 19:21:33.048 * Opening AOF incr file appendonly.aof.40.incr.aof on server start
cnvr-neteng-netbox-docker-redis-1                | 1:M 16 May 2023 19:21:33.048 * Ready to accept connections
cnvr-neteng-netbox-docker-redis-cache-1          | 1:C 16 May 2023 19:21:30.327 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
cnvr-neteng-netbox-docker-redis-cache-1          | 1:C 16 May 2023 19:21:30.328 # Redis version=7.0.10, bits=64, commit=00000000, modified=0, pid=1, just started
cnvr-neteng-netbox-docker-redis-cache-1          | 1:C 16 May 2023 19:21:30.328 # Configuration loaded
cnvr-neteng-netbox-docker-redis-cache-1          | 1:M 16 May 2023 19:21:30.328 * monotonic clock: POSIX clock_gettime
cnvr-neteng-netbox-docker-redis-cache-1          | 1:M 16 May 2023 19:21:30.329 * Running mode=standalone, port=6379.
cnvr-neteng-netbox-docker-redis-cache-1          | 1:M 16 May 2023 19:21:30.329 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
cnvr-neteng-netbox-docker-redis-cache-1          | 1:M 16 May 2023 19:21:30.329 # Server initialized
cnvr-neteng-netbox-docker-redis-cache-1          | 1:M 16 May 2023 19:21:30.329 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
cnvr-neteng-netbox-docker-redis-cache-1          | 1:M 16 May 2023 19:21:30.330 * Loading RDB produced by version 7.0.10
cnvr-neteng-netbox-docker-redis-cache-1          | 1:M 16 May 2023 19:21:30.330 * RDB age 12 seconds
cnvr-neteng-netbox-docker-redis-cache-1          | 1:M 16 May 2023 19:21:30.330 * RDB memory usage when created 0.92 Mb
cnvr-neteng-netbox-docker-redis-cache-1          | 1:M 16 May 2023 19:21:30.330 * Done loading RDB, keys loaded: 1, keys expired: 0.
cnvr-neteng-netbox-docker-redis-cache-1          | 1:M 16 May 2023 19:21:30.330 * DB loaded from disk: 0.000 seconds
cnvr-neteng-netbox-docker-redis-cache-1          | 1:M 16 May 2023 19:21:30.330 * Ready to accept connections
cnvr-neteng-netbox-docker-netbox-worker-1        | 🧬 loaded config '/etc/netbox/config/configuration.py'
cnvr-neteng-netbox-docker-netbox-worker-1        | 🧬 loaded config '/etc/netbox/config/extra.py'
cnvr-neteng-netbox-docker-netbox-worker-1        | 🧬 loaded config '/etc/netbox/config/logging.py'
cnvr-neteng-netbox-docker-netbox-worker-1        | 🧬 loaded config '/etc/netbox/config/plugins.py'
cnvr-neteng-netbox-docker-netbox-worker-1        | Traceback (most recent call last):
cnvr-neteng-netbox-docker-netbox-worker-1        |   File "/opt/netbox/netbox/manage.py", line 10, in <module>
cnvr-neteng-netbox-docker-netbox-housekeeping-1  | Interval set to 86400 seconds
cnvr-neteng-netbox-docker-netbox-housekeeping-1  | Tue May 16 19:22:04 UTC 2023
cnvr-neteng-netbox-docker-netbox-housekeeping-1  | 🧬 loaded config '/etc/netbox/config/configuration.py'
cnvr-neteng-netbox-docker-netbox-housekeeping-1  | 🧬 loaded config '/etc/netbox/config/extra.py'
cnvr-neteng-netbox-docker-netbox-housekeeping-1  | 🧬 loaded config '/etc/netbox/config/logging.py'
cnvr-neteng-netbox-docker-netbox-housekeeping-1  | 🧬 loaded config '/etc/netbox/config/plugins.py'
cnvr-neteng-netbox-docker-netbox-housekeeping-1  | [*] Clearing expired authentication sessions
cnvr-neteng-netbox-docker-netbox-housekeeping-1  |      Sessions cleared.
cnvr-neteng-netbox-docker-netbox-housekeeping-1  | [*] Checking for expired changelog records
cnvr-neteng-netbox-docker-netbox-housekeeping-1  |      No expired records found.
cnvr-neteng-netbox-docker-netbox-housekeeping-1  | [*] Checking for expired jobresult records
cnvr-neteng-netbox-docker-netbox-housekeeping-1  |      No expired records found.
cnvr-neteng-netbox-docker-netbox-housekeeping-1  | [*] Checking for latest release
cnvr-neteng-netbox-docker-netbox-housekeeping-1  |      Latest release: 3.5.1
cnvr-neteng-netbox-docker-netbox-housekeeping-1  | Finished.
cnvr-neteng-netbox-docker-netbox-1               | 🧬 loaded config '/etc/netbox/config/configuration.py'
cnvr-neteng-netbox-docker-netbox-1               | 🧬 loaded config '/etc/netbox/config/extra.py'
cnvr-neteng-netbox-docker-netbox-1               | 🧬 loaded config '/etc/netbox/config/logging.py'
cnvr-neteng-netbox-docker-netbox-1               | 🧬 loaded config '/etc/netbox/config/plugins.py'
cnvr-neteng-netbox-docker-netbox-1               | 💡 Superuser Username: admin, E-Mail: admin@example.com
cnvr-neteng-netbox-docker-netbox-1               | 🧬 loaded config '/etc/netbox/config/configuration.py'
cnvr-neteng-netbox-docker-netbox-1               | 🧬 loaded config '/etc/netbox/config/extra.py'
cnvr-neteng-netbox-docker-netbox-1               | 🧬 loaded config '/etc/netbox/config/logging.py'
cnvr-neteng-netbox-docker-netbox-1               | 🧬 loaded config '/etc/netbox/config/plugins.py'
cnvr-neteng-netbox-docker-netbox-1               | ✅ Initialisation is done.
cnvr-neteng-netbox-docker-netbox-1               | ⏳ Waiting for control socket to be created... (1/10)
cnvr-neteng-netbox-docker-netbox-1               | 2023/05/16 19:21:46 [warn] 7#7 Unit is running unprivileged, then it cannot use arbitrary user and group.
cnvr-neteng-netbox-docker-netbox-1               | 2023/05/16 19:21:46 [info] 7#7 unit 1.29.1 started
cnvr-neteng-netbox-docker-netbox-1               | 2023/05/16 19:21:46 [info] 22#22 discovery started
cnvr-neteng-netbox-docker-netbox-1               | 2023/05/16 19:21:46 [notice] 22#22 module: python 3.10.4 "/usr/lib/unit/modules/python3.10.unit.so"
cnvr-neteng-netbox-docker-netbox-1               | 2023/05/16 19:21:46 [info] 7#7 controller started
cnvr-neteng-netbox-docker-netbox-1               | 2023/05/16 19:21:46 [notice] 7#7 process 22 exited with code 0
cnvr-neteng-netbox-docker-netbox-1               | 2023/05/16 19:21:46 [info] 24#24 router started
cnvr-neteng-netbox-docker-netbox-1               | 2023/05/16 19:21:46 [info] 24#24 OpenSSL 3.0.2 15 Mar 2022, 30000020
cnvr-neteng-netbox-docker-netbox-1               | ⚙️ Applying configuration from /etc/unit/nginx-unit.json
cnvr-neteng-netbox-docker-netbox-1               | 2023/05/16 19:21:47 [info] 28#28 "netbox" prototype started
cnvr-neteng-netbox-docker-netbox-1               | 2023/05/16 19:21:47 [info] 29#29 "netbox" application started
cnvr-neteng-netbox-docker-netbox-1               | 🧬 loaded config '/etc/netbox/config/configuration.py'
cnvr-neteng-netbox-docker-netbox-1               | 🧬 loaded config '/etc/netbox/config/extra.py'
cnvr-neteng-netbox-docker-netbox-1               | 🧬 loaded config '/etc/netbox/config/logging.py'
cnvr-neteng-netbox-docker-netbox-1               | 🧬 loaded config '/etc/netbox/config/plugins.py'
cnvr-neteng-netbox-docker-netbox-1               | ✅ Unit configuration loaded successfully
cnvr-neteng-netbox-docker-netbox-1               | 2023/05/16 19:21:48 [notice] 7#7 process 20 exited with code 0
cnvr-neteng-netbox-docker-netbox-1               | 2023/05/16 19:22:00 [info] 39#39 "netbox" application started
cnvr-neteng-netbox-docker-netbox-1               | 🧬 loaded config '/etc/netbox/config/configuration.py'
cnvr-neteng-netbox-docker-netbox-1               | 🧬 loaded config '/etc/netbox/config/extra.py'
cnvr-neteng-netbox-docker-netbox-1               | 🧬 loaded config '/etc/netbox/config/logging.py'
cnvr-neteng-netbox-docker-netbox-1               | 🧬 loaded config '/etc/netbox/config/plugins.py'
cnvr-neteng-netbox-docker-netbox-1               | 127.0.0.1 - - [16/May/2023:19:22:03 +0000] "GET /api/ HTTP/1.1" 200 469 "-" "curl/7.81.0"
cnvr-neteng-netbox-docker-netbox-worker-1        |     execute_from_command_line(sys.argv)
cnvr-neteng-netbox-docker-netbox-worker-1        |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
cnvr-neteng-netbox-docker-netbox-worker-1        |     utility.execute()
cnvr-neteng-netbox-docker-netbox-worker-1        |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
cnvr-neteng-netbox-docker-netbox-worker-1        |     self.fetch_command(subcommand).run_from_argv(self.argv)
cnvr-neteng-netbox-docker-netbox-worker-1        |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 279, in fetch_command
cnvr-neteng-netbox-docker-netbox-worker-1        |     klass = load_command_class(app_name, subcommand)
cnvr-neteng-netbox-docker-netbox-worker-1        |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 48, in load_command_class
cnvr-neteng-netbox-docker-netbox-worker-1        |     module = import_module("%s.management.commands.%s" % (app_name, name))
cnvr-neteng-netbox-docker-netbox-worker-1        |   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
cnvr-neteng-netbox-docker-netbox-worker-1        |     return _bootstrap._gcd_import(name[level:], package, level)
cnvr-neteng-netbox-docker-netbox-worker-1        |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
cnvr-neteng-netbox-docker-netbox-worker-1        |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
cnvr-neteng-netbox-docker-netbox-worker-1        |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
cnvr-neteng-netbox-docker-netbox-worker-1        |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
cnvr-neteng-netbox-docker-netbox-worker-1        |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
cnvr-neteng-netbox-docker-netbox-worker-1        |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
cnvr-neteng-netbox-docker-netbox-worker-1        |   File "/opt/netbox/netbox/extras/management/commands/rqworker.py", line 3, in <module>
cnvr-neteng-netbox-docker-netbox-worker-1        |     from django_rq.management.commands.rqworker import Command as _Command
cnvr-neteng-netbox-docker-netbox-worker-1        |   File "/opt/netbox/venv/lib/python3.10/site-packages/django_rq/management/commands/rqworker.py", line 5, in <module>
cnvr-neteng-netbox-docker-netbox-worker-1        |     from rq import use_connection
cnvr-neteng-netbox-docker-netbox-worker-1        | ImportError: cannot import name 'use_connection' from 'rq' (/opt/netbox/venv/lib/python3.10/site-packages/rq/__init__.py)
```

### Content of docker-compose.override.yml

```yaml
version: '3.4'

services:
  netbox-worker: &netbox-common # these keys are used by netbox, netbox-worker, and netbox-housekeeping
    image: [redacted]/neteng/netbox-docker:v3.4.8-2.5.3 # this will be the same for dev vs prod
    env_file: env/cnvr-netbox.env # the contents of this file need to change for dev vs prod
    restart: always
    depends_on:
    - redis
    - redis-cache
  netbox:
    <<: *netbox-common
    ports:
      - 9253:8080
    environment:
      REMOTE_AUTH_ENABLED: "True"
      REMOTE_AUTH_BACKEND: "netbox.authentication.LDAPBackend"
    volumes:
      - ./scripts:/etc/netbox/scripts:z,ro
  netbox-housekeeping:
    <<: *netbox-common
  redis:
    restart: always
  redis-cache:
    restart: always

  postgres:
    command: "true"
    entrypoint: "true"
```

**Comment by FliesLikeABrick** [comment]
#1014 opened, though I am not sure how the maintainers would want to incorporate this only for NetBox < 3.5.1

**Comment by tobiasge** [comment]
We aren't building images for older versions of Netbox, as Netbox core also only patches the newest major version.

**Comment by FliesLikeABrick** [comment]
Ok thanks, we will re-evaluate our upgrade strategy.  We planned to deploy 3.4.latest instead of deploying 3.5.x immediately, and were surprised that 2.5.3 could not be used to build containers for 3.4.10
