### ISSUE TITLE
Database migration fails when upgrading to version 3.0.1

### ISSUE THREAD

**Issue by jonlarsdizparc** [netbox-community/netbox-docker#1311]
### Current Behavior

Upgraded to 3.0.1 from 2.9.1, and started the docker compose manifest. Database migration fails on startup.

### Expected Behavior

Expected a successful database migration on startup.

### Docker Compose Version

Using built in "docker compose"

### Docker Version

```text
Client: Docker Engine - Community
 Version:           25.0.2
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        29cf629
 Built:             Thu Feb  1 00:23:17 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          25.0.2
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       fce6e0c
  Built:            Thu Feb  1 00:23:17 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### The git Revision

5add31ee7a55da8872efaa95278037a0e34020d5

### The git Status

```text
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
modified:   configuration/configuration.py
modified:   env/netbox.env

Untracked files:
  (use "git add <file>..." to include in what will be committed)
Dockerfile-Plugins
plugin_requirements.txt
```

### Startup Command

docker compose up -d

### NetBox Logs

```text
⚙ Applying database migrations
溺 loaded config '/etc/netbox/config/configuration.py'
溺 loaded config '/etc/netbox/config/extra.py'
溺 loaded config '/etc/netbox/config/logging.py'
溺 loaded config '/etc/netbox/config/plugins.py'
Traceback (most recent call last):
  File "/opt/netbox/netbox/./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/management/base.py", line 107, in wrapper
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/management/commands/migrate.py", line 120, in handle
    executor.loader.check_consistent_history(connection)
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/db/migrations/loader.py", line 327, in check_consistent_history
    raise InconsistentMigrationHistory(
django.db.migrations.exceptions.InconsistentMigrationHistory: Migration circuits.0044_circuit_groups is applied before its dependency extras.0119_notifications on databas
e 'default'.
```

### Content of docker-compose.override.yml

```yaml
version: '3.4'
services:
  netbox:
    environment:
      LOGIN_REQUIRED: True
      ALLOWED_HOSTS: '*'
      CSRF_TRUSTED_ORIGINS: https://<fqdn>
      ALLOWED_URL_SCHEMES: https
    ports:
      - "8080:8080"
    restart: unless-stopped
  netbox-worker:
    restart: unless-stopped
  netbox-housekeeping:
    restart: unless-stopped
  postgres:
    restart: unless-stopped
  redis:
    restart: unless-stopped
  redis-cache:
    restart: unless-stopped
```

**Comment by tobiasge** [comment]
This is not a problem of the Docker Image, but with Netbox itself.

I have seen this error also, when I tried to go from a beta release to the final version. I think that is not supported by Netbox. You have to update from Netbox 4.0.x directly to Netbox 4.1.

**Comment by thomas-mc-work** [comment]
So would that mean that a beta release is kind of a dead end? Or are there any options to go forward?
