### ISSUE TITLE
Image tag 2.6.7-ldap fails to start, "libc not found"

### ISSUE THREAD

**Issue by ananace** [netbox-community/netbox-docker#179]
Error log;
```
[...]
0 static files copied to '/opt/netbox/netbox/static', 344 unmodified.
✅ Initialisation is done.
Traceback (most recent call last):
  File "/usr/local/bin/gunicorn", line 5, in <module>
    from gunicorn.app.wsgiapp import run
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 9, in <module>
    from gunicorn.app.base import Application
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 12, in <module>
    from gunicorn.arbiter import Arbiter
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 16, in <module>
    from gunicorn import sock, systemd, util
  File "/usr/local/lib/python3.7/site-packages/gunicorn/sock.py", line 14, in <module>
    from gunicorn.socketfromfd import fromfd
  File "/usr/local/lib/python3.7/site-packages/gunicorn/socketfromfd.py", line 26, in <module>
    raise OSError('libc not found')
OSError: libc not found
``` 

My preliminary googling on this seems to point to gunicorn version 20 being the culprit.

Image tag 2.6.6-ldap still seems to work fine.

**Comment by MyIgel** [comment]
Same for the current `:latest`

**Comment by tobiasge** [comment]
Thanks for the report. I think this is related to the new version of gunicorn. See: https://stackoverflow.com/questions/58786695/how-to-address-oserror-libc-not-found-raised-on-gunicorn-exec-of-flask-app-in

I will pin the version to on <20.0.0 for now.
