### ISSUE TITLE
Tag 2.7.1-ldap fails to start due to old redis configuration

### ISSUE THREAD

**Issue by ananace** [netbox-community/netbox-docker#227]
## Current Behavior
 

Tested upgrading one instance of netbox to the 2.7.1-ldap tag on dockerhub, but it's failing to start due to apparently still using the 2.6 configuration format for redis.

 
## Expected Behavior
 

Netbox starts and runs
 
## Debug Information

Running in Kubernetes, using CRI-O, so can't give any docker information outputs

The output of `docker-compose logs netbox`: (`kubectl logs -l app=netbox -c netbox`)

```text
⏳ Waiting on DB...
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 361, in execute
    self.check()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 64, in _run_checks
    issues = run_checks(tags=[Tags.database])
  File "/usr/local/lib/python3.7/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.7/site-packages/django/core/checks/database.py", line 9, in check_database_backends
    for conn in connections.all():
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 216, in all
    return [self[alias] for alias in self]
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 213, in __iter__
    return iter(self.databases)
  File "/usr/local/lib/python3.7/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 147, in databases
    self._databases = settings.DATABASES
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/netbox/netbox/netbox/settings.py", line 162, in <module>
    "REDIS section in configuration.py is missing webhooks subsection."
django.core.exceptions.ImproperlyConfigured: REDIS section in configuration.py is missing webhooks subsection.
```

**Comment by cimnine** [comment]
Yes this is known. Support for Netbox 2.7 will be added in version 0.21.0 of this project. See also #224.

**Comment by ananace** [comment]
Why are there tags named just like the production-ready ones if they don't work without modification though? Feels really odd.

**Comment by cimnine** [comment]
Because this is an automated process, not a manual one.

**Comment by cimnine** [comment]
FYI: With the recent release we've changed to a new build system based on Github Action Workflows. The new build system includes tests for every image that is built. If the tests do not pass, the image is not pushed to Docker Hub. It would have prevented this issue altogether.
