### ISSUE TITLE
cannot import name 'ColorChoices' from 'utilities.choices'

### ISSUE THREAD

**Issue by anubisg1** [netbox-community/netbox-docker#312]
## Current Behavior

netbox builds but won't start. I thinking that fixing https://github.com/netbox-community/netbox-docker/issues/303  broke older netbox  versions.
Unfortuantely it's not an option for me to run the latest version of netbox yet.

## Expected Behavior

application should boot properly

## Debug Information

The output of `docker-compose version`: `1.17.0`
The output of `docker version`: `2.6.1`
The output of `git rev-parse HEAD`: `e9a9d9b70bb1afaaeb4d120ce37263372f67c6af`
The command you used to start the project: `
export VERSION=v2.7.6
docker-compose pull netbox
docker-compose up -d
`
The output of `docker-compose logs netbox`:

```netbox_1         | Operations to perform:
netbox_1         |   Apply all migrations: admin, auth, circuits, contenttypes, dcim, extras, ipam, secrets, sessions, taggit, tenancy, users, virtualization
netbox_1         | Running migrations:
netbox_1         |   No migrations to apply.
netbox_1         | 💡 Superuser Username: admin, E-Mail: admin@example.com
netbox_1         | ▶️ Running the startup script /opt/netbox/startup_scripts/000_users.py
netbox_1         | ▶️ Running the startup script /opt/netbox/startup_scripts/010_groups.py
netbox_1         | ▶️ Running the startup script /opt/netbox/startup_scripts/020_custom_fields.py
netbox_1         | ▶️ Running the startup script /opt/netbox/startup_scripts/030_regions.py
netbox_1         | ▶️ Running the startup script /opt/netbox/startup_scripts/040_sites.py
netbox_1         | ▶️ Running the startup script /opt/netbox/startup_scripts/050_manufacturers.py
netbox_1         | ▶️ Running the startup script /opt/netbox/startup_scripts/060_device_types.py
netbox_1         | ▶️ Running the startup script /opt/netbox/startup_scripts/070_rack_roles.py
netbox_1         | Traceback (most recent call last):
netbox_1         |   File "./manage.py", line 10, in <module>
netbox_1         |     execute_from_command_line(sys.argv)
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
netbox_1         |     utility.execute()
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
netbox_1         |     self.fetch_command(subcommand).run_from_argv(self.argv)
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
netbox_1         |     self.execute(*args, **cmd_options)
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
netbox_1         |     output = self.handle(*args, **options)
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/shell.py", line 92, in handle
netbox_1         |     exec(sys.stdin.read())
netbox_1         |   File "<string>", line 1, in <module>
netbox_1         |   File "/usr/local/lib/python3.7/runpy.py", line 280, in run_path
netbox_1         |     run_name, mod_spec, pkg_name).copy()
netbox_1         |   File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
netbox_1         |     exec(code, run_globals)
netbox_1         |   File "../startup_scripts/__main__.py", line 19, in <module>
netbox_1         |     runpy.run_path(f.path)
netbox_1         |   File "/usr/local/lib/python3.7/runpy.py", line 263, in run_path
netbox_1         |     pkg_name=pkg_name, script_name=fname)
netbox_1         |   File "/usr/local/lib/python3.7/runpy.py", line 96, in _run_module_code
netbox_1         |     mod_name, mod_spec, pkg_name, script_name)
netbox_1         |   File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
netbox_1         |     exec(code, run_globals)
netbox_1         |   File "/opt/netbox/startup_scripts/070_rack_roles.py", line 2, in <module>
netbox_1         |     from utilities.choices import ColorChoices
netbox_1         | ImportError: cannot import name 'ColorChoices' from 'utilities.choices' (/opt/netbox/netbox/utilities/choices.py)
netboxdocker_netbox_1 exited with code 1
```

**Comment by tobiasge** [comment]
See the release notes for 0.24.1:

> This version is compatible with Netbox 2.8.5 (and hopefully later versions as well).
> ⚠️ This version is not compatible with Netbox 2.8.4 or lower!

If you're using a Netbox version lower than 2.8.5, you should use netbox-docker version 0.24.0
