### ISSUE TITLE
ImportError: cannot import name 'CustomFieldChoice'

### ISSUE THREAD

**Issue by cimnine** [netbox-community/netbox-docker#337]
## Current Behavior

```
ImportError: cannot import name 'CustomFieldChoice' from 'extras.models' (/opt/netbox/netbox/extras/models/__init__.py)
```

This will happen with the next Netbox release :-/

## Expected Behavior

No error.

## Debug Information

```
2020-09-21T05:48:48.8017175Z ▶️ ./build-next.sh 
2020-09-21T05:48:48.8018381Z 🕶 Performing unauthenticated Github API calls. This might result in lower Github rate limits!
2020-09-21T05:48:48.8019402Z ▶️ ./build.sh develop-2.10
2020-09-21T05:48:48.8020664Z 🌐 Checking out 'develop-2.10' of netbox from the url 'https://github.com/netbox-community/netbox.git' into '.netbox'
2020-09-21T05:48:50.1761279Z ✅ Checked out netbox
2020-09-21T05:48:50.1873547Z 🏭 Building the following targets: main ldap
2020-09-21T05:48:50.1895680Z 🏗 Building the target 'main'
2020-09-21T05:48:50.9721445Z 🐳 Building the Docker image 'docker.io/netboxcommunity/netbox:develop-2.10'.
```

```
... 🐳🐳🐳 Start testing 'docker.io/netboxcommunity/netbox:develop-2.10-ldap'
... Traceback (most recent call last):

2020-09-21T05:58:26.5655561Z   File "./manage.py", line 10, in <module>
2020-09-21T05:58:26.5656358Z     execute_from_command_line(sys.argv)
2020-09-21T05:58:26.5658070Z   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
2020-09-21T05:58:26.5659441Z     utility.execute()
2020-09-21T05:58:26.5661001Z   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
2020-09-21T05:58:26.5662340Z     self.fetch_command(subcommand).run_from_argv(self.argv)
2020-09-21T05:58:26.5664057Z   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 330, in run_from_argv
2020-09-21T05:58:26.5665260Z     self.execute(*args, **cmd_options)
2020-09-21T05:58:26.5666818Z   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 371, in execute
2020-09-21T05:58:26.5668005Z     output = self.handle(*args, **options)
2020-09-21T05:58:26.5669882Z   File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/shell.py", line 92, in handle
2020-09-21T05:58:26.5671062Z     exec(sys.stdin.read())
2020-09-21T05:58:26.5671756Z   File "<string>", line 1, in <module>
2020-09-21T05:58:26.5672600Z   File "/usr/local/lib/python3.7/runpy.py", line 280, in run_path
2020-09-21T05:58:26.5673445Z     run_name, mod_spec, pkg_name).copy()
2020-09-21T05:58:26.5674568Z   File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
2020-09-21T05:58:26.5675382Z     exec(code, run_globals)
2020-09-21T05:58:26.5676155Z   File "../startup_scripts/__main__.py", line 25, in <module>
2020-09-21T05:58:26.5676930Z     runpy.run_path(f.path)
2020-09-21T05:58:26.5677749Z   File "/usr/local/lib/python3.7/runpy.py", line 263, in run_path
2020-09-21T05:58:26.5678620Z     pkg_name=pkg_name, script_name=fname)
2020-09-21T05:58:26.5679685Z   File "/usr/local/lib/python3.7/runpy.py", line 96, in _run_module_code
2020-09-21T05:58:26.5680625Z     mod_name, mod_spec, pkg_name, script_name)
2020-09-21T05:58:26.5681512Z   File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
2020-09-21T05:58:26.5682310Z     exec(code, run_globals)
2020-09-21T05:58:26.5683214Z   File "/opt/netbox/startup_scripts/020_custom_fields.py", line 1, in <module>
2020-09-21T05:58:26.5684624Z     from extras.models import CustomField, CustomFieldChoice
2020-09-21T05:58:26.5686766Z ImportError: cannot import name 'CustomFieldChoice' from 'extras.models' (/opt/netbox/netbox/extras/models/__init__.py)
```

**Comment by weisdd** [comment]
It needs to be further investigated, but, as a hint, the support for CustomFieldChoice was dropped in this PR: https://github.com/netbox-community/netbox/pull/5145

**Comment by cimnine** [comment]
The Netbox maintainers simplified the handling of custom fields in their backend quite a bit, which resulted in some rework on our side. But – unless further changes to the custom fields are ahead – we're now ready for v2.10.x (at least the initializers are). Thank you for the hint, btw!

**Comment by Jamesits** [comment]
We actually hit this while updating to docker image `v2.10.0`.

One screenshot if it helps:
![image](https://user-images.githubusercontent.com/1297257/102297924-21806a00-3f8b-11eb-9f5b-d9b71319923b.png)

Edit:
updated the docker compose repo and everything is now working.

**Comment by SteffenViperKoch** [comment]
> We actually hit this while updating to docker image `v2.10.0`.
> 
> One screenshot if it helps:
> ![image](https://user-images.githubusercontent.com/1297257/102297924-21806a00-3f8b-11eb-9f5b-d9b71319923b.png)
> 
> Edit:
> updated the docker compose repo and everything is now working.

how?

EDIT: figured out myself... reading AND understanding helps a lot --> git pull did the trick... completely forgot about the repo...

**Comment by zenidon** [comment]
I just hit this bug as well.  First did a docker-compose pull to the get the latest version, hit this bug. Did a git pull and another docker-compose pull, but I am still getting the error.  Tried rolling back to v2.9.10, but the DB script already ran...

Going to roll back and restore the DB, but curious on the fix for this.

Thank you!

**Comment by SteffenViperKoch** [comment]
It needed a **docker-compose down**, **docker-compose pull** and **docker-compose up -d** to work

**Comment by weisdd** [comment]
@zenidon also, you need to make sure you followed [all the instructions over here](https://github.com/netbox-community/netbox-docker/releases/tag/0.27.0).

**Comment by SteffenViperKoch** [comment]
wasn't necessary here... just updated another instance from 2.9.9 to 2.10.2

**Comment by SteffenViperKoch** [comment]
okay... it **WAS** necessary ;-)

**Comment by zenidon** [comment]
Thank you, I think that link was the missing piece of the puzzle.  Thank
you very much!
