### ISSUE TITLE
Failing to boot due to "SyntaxError: EOL while scanning string literal"

### ISSUE THREAD

**Issue by Kasea** [netbox-community/netbox-docker#362]
## Current Behavior
Does not want to boot up due to "SyntaxError".

I had a working netbox setup on my kubernetes cluster, I recently remade the cluster (with the same database (postgres) as before). I used the exact same netbox.yaml files to recreate the setup, but it did not want to boot up properly.

I get the following from `kubectl logs netbox-<id> netbox`
```
Operations to perform:
  Apply all migrations: admin, auth, circuits, contenttypes, dcim, extras, ipam, secrets, sessions, taggit, tenancy, users, virtualization
Running migrations:
  No migrations to apply.
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/shell.py", line 92, in handle
    exec(sys.stdin.read())
  File "<string>", line 4
    u=User.objects.create_superuser('admin', 'admin@example.com', '<my password>
                                                                                                                                      ^
SyntaxError: EOL while scanning string literal
```

## Expected Behavior
I expect it to boot up without any issues.

I experienced it failing to boot up due to "SyntaxError"

## Debug Information
The password I used contains no special characters, it's all within A-Za-z0-9

Server is running kubernetes 1.16.2.

I am experiencing the same error message on all versions of the image from 2.6.1->2.6.12 and 2.7 -> 2.9 (did not check specific sub versions)

Note: I'm using the -ldap version of the image.

**Comment by Kasea** [comment]
turns out I forgot to include `-n` in my echo statement when I made the base64, turns out there was a \n in the base64.
