### ISSUE TITLE
startup script 020_custom_fields.py has a static reference to an /opt/netbox folder that crashes netbox 2.10

### ISSUE THREAD

**Issue by csallen1204** [netbox-community/netbox-docker#373]
After upgrading/migrating to Netbox 2.10, the container would crash with this error:
```
Dec 15 20:25:32 netbox docker-compose: #033[33mnetbox_1         |#033[0m Traceback (most recent call last):
Dec 15 20:25:32 netbox docker-compose: #033[33mnetbox_1         |#033[0m   File "/opt/netbox/netbox/./manage.py", line 10, in <module>
Dec 15 20:25:32 netbox docker-compose: #033[33mnetbox_1         |#033[0m 🧬 loaded config '/etc/netbox/config/configuration.py'
Dec 15 20:25:32 netbox docker-compose: #033[33mnetbox_1         |#033[0m 🧬 loaded config '/etc/netbox/config/configuration.py'
Dec 15 20:25:32 netbox docker-compose: #033[33mnetbox_1         |#033[0m 🧬 loaded config '/etc/netbox/config/extra.py'
Dec 15 20:25:32 netbox docker-compose: #033[33mnetbox_1         |#033[0m ▶️ Running the startup script /opt/netbox/startup_scripts/000_users.py
Dec 15 20:25:32 netbox docker-compose: #033[33mnetbox_1         |#033[0m ▶️ Running the startup script /opt/netbox/startup_scripts/010_groups.py
Dec 15 20:25:32 netbox docker-compose: #033[33mnetbox_1         |#033[0m ▶️ Running the startup script /opt/netbox/startup_scripts/020_custom_fields.py
Dec 15 20:25:32 netbox docker-compose: #033[33mnetbox_1         |#033[0m     execute_from_command_line(sys.argv)
Dec 15 20:25:32 netbox docker-compose: #033[33mnetbox_1         |#033[0m   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
Dec 15 20:25:32 netbox docker-compose: #033[33mnetbox_1         |#033[0m     utility.execute()
Dec 15 20:25:32 netbox docker-compose: #033[33mnetbox_1         |#033[0m   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
Dec 15 20:25:32 netbox docker-compose: #033[33mnetbox_1         |#033[0m     self.fetch_command(subcommand).run_from_argv(self.argv)
Dec 15 20:25:32 netbox docker-compose: #033[33mnetbox_1         |#033[0m   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 330, in run_from_argv
Dec 15 20:25:32 netbox docker-compose: #033[33mnetbox_1         |#033[0m     self.execute(*args, **cmd_options)
Dec 15 20:25:32 netbox docker-compose: #033[33mnetbox_1         |#033[0m   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 371, in execute
Dec 15 20:25:32 netbox docker-compose: #033[33mnetbox_1         |#033[0m     output = self.handle(*args, **options)
Dec 15 20:25:32 netbox docker-compose: #033[33mnetbox_1         |#033[0m   File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/shell.py", line 93, in handle
Dec 15 20:25:32 netbox docker-compose: #033[33mnetbox_1         |#033[0m     exec(sys.stdin.read())
Dec 15 20:25:32 netbox docker-compose: #033[33mnetbox_1         |#033[0m   File "<string>", line 1, in <module>
Dec 15 20:25:32 netbox docker-compose: #033[33mnetbox_1         |#033[0m   File "/usr/local/lib/python3.9/runpy.py", line 285, in run_path
Dec 15 20:25:32 netbox docker-compose: #033[33mnetbox_1         |#033[0m     return _run_code(code, mod_globals, init_globals,
Dec 15 20:25:32 netbox docker-compose: #033[33mnetbox_1         |#033[0m   File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
Dec 15 20:25:32 netbox docker-compose: #033[33mnetbox_1         |#033[0m     exec(code, run_globals)
Dec 15 20:25:32 netbox docker-compose: #033[33mnetbox_1         |#033[0m   File "../startup_scripts/__main__.py", line 25, in <module>
Dec 15 20:25:32 netbox docker-compose: #033[33mnetbox_1         |#033[0m     runpy.run_path(f.path)
Dec 15 20:25:32 netbox docker-compose: #033[33mnetbox_1         |#033[0m   File "/usr/local/lib/python3.9/runpy.py", line 268, in run_path
Dec 15 20:25:32 netbox docker-compose: #033[33mnetbox_1         |#033[0m     return _run_module_code(code, init_globals, run_name,
Dec 15 20:25:32 netbox docker-compose: #033[33mnetbox_1         |#033[0m   File "/usr/local/lib/python3.9/runpy.py", line 97, in _run_module_code
Dec 15 20:25:32 netbox docker-compose: #033[33mnetbox_1         |#033[0m     _run_code(code, mod_globals, init_globals,
Dec 15 20:25:32 netbox docker-compose: #033[33mnetbox_1         |#033[0m   File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
Dec 15 20:25:32 netbox docker-compose: #033[33mnetbox_1         |#033[0m     exec(code, run_globals)
Dec 15 20:25:32 netbox docker-compose: #033[33mnetbox_1         |#033[0m   File "/opt/netbox/startup_scripts/020_custom_fields.py", line 1, in <module>
Dec 15 20:25:32 netbox docker-compose: #033[33mnetbox_1         |#033[0m     from extras.models import CustomField, CustomFieldChoice
Dec 15 20:25:32 netbox docker-compose: #033[33mnetbox_1         |#033[0m ImportError: cannot import name 'CustomFieldChoice' from 'extras.models' (/opt/netbox/netbox/extras/models/__init__.py)
```

It was like this when I was running version 2.9 but it didn't seem to be an issue then. Looking at the 020_custom_fields.py file I confirmed that it's trying to load custom_fields.yml from /opt/netbox in the python script: 

```
customfields = load_yaml('/opt/netbox/initializers/custom_fields.yml')
```

I corrected the path to what my folder path is and then it worked for me.

**Comment by cimnine** [comment]
Please fill in the full bug report template. I will close this issue because you did not provide enough information to confirm that this is a bug.

But as far as I can tell you did not upgrade properly. `CustomFieldChoice` is no longer a type in Netbox 2.10 and therefore the script fails. We have fixed our script in [version 0.27.0](https://github.com/netbox-community/netbox-docker/releases/tag/0.27.0). You need to update your folder.
