### ISSUE TITLE
plugin usage not working - Module not found

### ISSUE THREAD

**Issue by rgarcia89** [netbox-community/netbox-docker#414]
## Current Behavior

When trying to installed some additional plugins following the instructions on https://github.com/netbox-community/netbox-docker/wiki/Using-Netbox-Plugins

```
FROM netboxcommunity/netbox:latest-ldap

COPY ./plugin_requirements.txt /
RUN /opt/netbox/venv/bin/pip install --no-cache --no-warn-script-location -r /plugin_requirements.txt
```

where plugin_requirements.txt looks like
```
netbox-plugin-auth-saml2
django3-auth-saml2
```

I am overwriting the extras.py with a configmap that for now includes the following:
```
  extra.py: |
    PLUGINS = ['django3-auth-saml2']
```

## Expected Behavior

Netbox should start success as the plugin is installed and available in the correct environment

## Debug Information

The output of `docker-compose version`: `1.28.2`
The output of `docker version`: `19.3.14`
The output of `git rev-parse HEAD`: `XXXXX`
The command you used to start the project: `XXXXX`

The output of `docker inspect netboxcommunity/netbox:latest --format "{{json .Config.Labels}}"`:

```json
{
  "BUILD_REASON": "alpine netbox-docker",
  "NETBOX_GIT_BRANCH": "HEAD",
  "NETBOX_GIT_REF": "856d2e317605011e16a17bd87062721737ce3474",
  "NETBOX_GIT_URL": "https://github.com/netbox-community/netbox.git",
  "ORIGINAL_TAG": "docker.io/netboxcommunity/netbox:v2.10.4-ldap",
  "org.label-schema.build-date": "2021-01-29T09:48+00:00",
  "org.label-schema.description": "A container based distribution of Netbox, the free and open IPAM and DCIM solution.",
  "org.label-schema.name": "Netbox Docker",
  "org.label-schema.schema-version": "1.0",
  "org.label-schema.url": "https://github.com/netbox-community/netbox-docker",
  "org.label-schema.usage": "https://github.com/netbox-community/netbox-docker/wiki",
  "org.label-schema.vcs-ref": "ed6256172fd6242e7d9f4b07f6a00b8ba9dc5fbc",
  "org.label-schema.vcs-url": "https://github.com/netbox-community/netbox-docker.git",
  "org.label-schema.vendor": "The netbox-docker contributors.",
  "org.label-schema.version": "1.0.0",
  "org.opencontainers.image.authors": "The netbox-docker contributors.",
  "org.opencontainers.image.created": "2021-01-29T09:48+00:00",
  "org.opencontainers.image.description": "A container based distribution of Netbox, the free and open IPAM and DCIM solution.",
  "org.opencontainers.image.documentation": "https://github.com/netbox-community/netbox-docker/wiki",
  "org.opencontainers.image.licenses": "Apache-2.0",
  "org.opencontainers.image.revision": "ed6256172fd6242e7d9f4b07f6a00b8ba9dc5fbc",
  "org.opencontainers.image.source": "https://github.com/netbox-community/netbox-docker.git",
  "org.opencontainers.image.title": "Netbox Docker",
  "org.opencontainers.image.url": "https://github.com/netbox-community/netbox-docker",
  "org.opencontainers.image.vendor": "The netbox-docker contributors.",
  "org.opencontainers.image.version": "1.0.0"

}
```

The output of `docker-compose logs netbox`:

```text
```
ModuleNotFoundError: No module named 'django3-auth-saml2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/base.py", line 82, in wrapped
    saved_locale = translation.get_language()
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/utils/translation/__init__.py", line 254, in get_language
    return _trans.get_language()
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/utils/translation/__init__.py", line 57, in __getattr__
    if settings.USE_I18N:
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 83, in __getattr__
    self._setup(name)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 70, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 177, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/netbox/netbox/netbox/settings.py", line 594, in <module>
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Unable to import plugin django3-auth-saml2: Module not found. Check that the plugin module has been installed within the correct Python environment.
```
```

**Comment by cimnine** [comment]
Perhaps silly questions, but:

- Did you override the image for the Netbox service to the one you've built, e.g. in `docker-compose.override.yml`?
- Did you _stop and remove_ the original container? I.e. `docker-compose rm -s netbox && docker-compose up netbox`

**Comment by rgarcia89** [comment]
Hi @cimnine thanks for asking.
I once got told, there are no silly questions. Only silly answers 😉

I am running netbox within kubernetes. So I have run the dockerfile build from a gitlab runner. I have also looked into the image and into the correct pip env, where a pip list proved the existence of the package.

**Comment by cimnine** [comment]
I have not seen this before (as I first thought this to be a thread on our GH Discussion board), but I ask you to update your bug report to follow the template as good as you can. Else it's hard for us to debug. Case in point: It would have made my question / your answer redundant, because in the template we ask how you run Netbox Docker.

That said, please try your plugin locally in the environment we provide, to rule out all of the eventualities that come with Kubernetes.

**Comment by rgarcia89** [comment]
@cimnine does this match your requested template now?

**Comment by tobiasge** [comment]
When I search for `netbox-plugin-auth-saml2`, I find [this](https://github.com/jeremyschulman/netbox-plugin-auth-saml2) plugin.
I presume it is the one you want to use. In the Readme of this project you can actually see that the `PLUGINS` line should look like this:
```python
PLUGINS = ['django3_saml2_nbplugin']
```
But in your configuration you have this:
```python
PLUGINS = ['django3-auth-saml2']
```

I just tried starting a container with your build configuration. When using the correct `PLUGINS` setting, the container is starting without a problem. You will also need to use the modified image for the netbox-worker container.

**Comment by barmalej1** [comment]
For this plugin to work you also need to add this line in Dockerfile-Plugins:

RUN apk add --no-cache xmlsec

**Comment by josiasal** [comment]
Hi, I'm facing the exact same problem with that plugin.

This `django3_saml2_nbplugin` seems to be a typo. I could not find a module with that name.

In the `Docker-Plugins` file I have this line (as indicated in the official guide):

```Dockerfile
RUN /opt/netbox/venv/bin/pip install  --no-warn-script-location -r /plugin_requirements.txt
```

I can see the plugin being installed while building the docker image. Later, the startup scripts crash due to the same error reported before:

```shell
raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Unable to import plugin django3-auth-saml2: Module not found. Check that the plugin module has been installed within the correct Python environment.
``` 

Is this a problem with the Python environment?

I have tried the suggestion from @barmalej1: `RUN apk add --no-cache xmlsec`. It does not solve the issue.

Thank you.

**Comment by barmalej1** [comment]
venv needs to be activated first

`RUN . /opt/netbox/venv/bin/activate && pip install  --no-warn-script-location -r /plugin_requirements.txt`

The correct name is `django3-auth-saml2`

**Comment by josiasal** [comment]
Hi @barmalej1, thanks for the prompt reply.

This is the Dockerfile:

```Dockerfile
FROM netboxcommunity/netbox:v2.11.2

COPY ./plugin_requirements.txt /

RUN . /opt/netbox/venv/bin/activate && \
    pip install --no-warn-script-location -r /plugin_requirements.txt

RUN apk add --no-cache xmlsec
```
The plugin_requirements.txt file:

```txt
django3-auth-saml2==0.2.0
```

The plugin is included in the config:

```python
PLUGINS = ["django3-auth-saml2"]
```

I also added the specific configuration but I'll skip that content.

While building the Dockerfile, I can see it worked fine:

```shell
Successfully installed defusedxml-0.7.1 django3-auth-saml2-0.2.0 netbox-plugin-auth-saml2-2.3 pyOpenSSL-20.0.1 pysaml2-5.0.0
```
---

I still get this error:

```shell
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/base.py", line 86, in wrapped
    saved_locale = translation.get_language()
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/utils/translation/__init__.py", line 254, in get_language
    return _trans.get_language()
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/utils/translation/__init__.py", line 57, in __getattr__
    if settings.USE_I18N:
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/netbox/netbox/netbox/settings.py", line 603, in <module>
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Unable to import plugin django3-auth-saml2: Module not found. Check that the plugin module has been installed within the correct Python environment.
❌ Waited 30s or more for the DB to become ready.
```

**Comment by barmalej1** [comment]
I am currently running 2.10, haven't tried 2.11 yet. I have these 2 lines in my plugin_requirements.txt

```
django3-auth-saml2
netbox-plugin-auth-saml2
```

And here is my config:

```
PLUGINS = ['django3_saml2_nbplugin']

PLUGINS_CONFIG = {
    'django3_saml2_nbplugin': {
        ...
    }
}
```
I also added nginx container back, since I couldn't figure out if it was possible to rewrite URL using nginx unit. I have the following added to nginx config:

```
server {
        listen      8080 default_server;
        access_log  off;
        server_name _;

        location /login/ {
            proxy_pass http://netbox:8080/api/plugins/sso/login/;
        }
 
        location /sso/ {
            proxy_pass http://netbox:8080/api/plugins/sso/; 
        }
 
        location / {
            proxy_pass http://netbox:8080;
        }
    }
```

For this to work I had to set the port for Netbox container to 8080

**Comment by josiasal** [comment]
Thanks @barmalej1, it helped me a lot.

As you said, nginx unit does not support URL rewrites. How did you make it work? Have you uninstalled unit from the container and installed regular nginx? Are you using both a the same time?

**Comment by barmalej1** [comment]
Using both at the same time

**Comment by josiasal** [comment]
Thank you @barmalej1. I decided to go with that login button above the form and use the `SSO_ACS_URL` parameter. It is working nicely and I will stick with nginx unit for now.

**Comment by Gagobert** [comment]
Hello, anyone still running this with a later version?
