### ISSUE TITLE
ImportError: cannot import name 'Location' from 'dcim.models'

### ISSUE THREAD

**Issue by timrabl** [netbox-community/netbox-docker#521]
## Current Behavior

After performing the steps in the `Expected Behavior` section, the compose stack or the netbox container does not start.  
It stops due to the following error message:

`ImportError: cannot import name 'Location' from 'dcim.models' (/opt/netbox/netbox/dcim/models/__init__.py)`

## Expected Behavior

After the steps below have been carried out, the Netbox container or rather the docker-compose stack should start and the startup scripts should run successfully.  
Afterwards the web interface should then be accessible under the specified port in the `docker-compose.override.yml` file.

1. Cloning the Github repository:
`git clone https://github.com/netbox-community/netbox-docker.git`.

2. Navigating into the `netbox-docker` directory:
`cd netbox-docker`

3. Creating the `docker-compose.override.yml` file:
```sh
tee docker-compose.override.yml <<EOF
version: '3.4'
services:
  netbox:
    ports:
      - 8000:8080
EOF
```

4. Starting the compose stack:
`docker-compose up -d`

5. Watching the logs and wait for successful startup:
`docker-compose logs -f --tail=200`

## Debug Information

The output of `docker-compose version`:
```text
docker-compose version 1.29.2, build unknown
docker-py version: 5.0.0
CPython version: 3.9.5
OpenSSL version: OpenSSL 1.1.1k  25 Mar 2021
```

The output of `docker version`:
```text
docker version
Client: Docker Engine - Community
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.16.3
 Git commit:        370c289
 Built:             Mon Apr 12 13:01:13 2021
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.3
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       46229ca
  Built:            Fri Jan 29 14:32:07 2021
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

The output of `git rev-parse HEAD`: 
```text
676ca798cd684ce30fca2692180e680d2becf76e
```

The command you used to start the project:
```sh
docker-compose up -d
```

The output of `docker inspect netboxcommunity/netbox:latest --format "{{json .Config.Labels}}"`:

```json
{
  "BUILD_REASON": "alpine netbox netbox-docker",
  "NETBOX_GIT_BRANCH": "HEAD",
  "NETBOX_GIT_REF": "47abd62c55c60d5c2f59efad6fe8ea3b2a992bf6",
  "NETBOX_GIT_URL": "https://github.com/netbox-community/netbox.git",
  "ORIGINAL_TAG": "docker.io/netboxcommunity/netbox:v2.10.5",
  "org.label-schema.build-date": "2021-02-25T05:48+00:00",
  "org.label-schema.description": "A container based distribution of NetBox, the free and open IPAM and DCIM solution.",
  "org.label-schema.name": "NetBox Docker",
  "org.label-schema.schema-version": "1.0",
  "org.label-schema.url": "https://github.com/netbox-community/netbox-docker",
  "org.label-schema.usage": "https://github.com/netbox-community/netbox-docker/wiki",
  "org.label-schema.vcs-ref": "c80fb19507679938528817ab8a9b03514bd1e8be",
  "org.label-schema.vcs-url": "https://github.com/netbox-community/netbox-docker.git",
  "org.label-schema.vendor": "The netbox-docker contributors.",
  "org.label-schema.version": "1.0.2",
  "org.opencontainers.image.authors": "The netbox-docker contributors.",
  "org.opencontainers.image.created": "2021-02-25T05:48+00:00",
  "org.opencontainers.image.description": "A container based distribution of NetBox, the free and open IPAM and DCIM solution.",
  "org.opencontainers.image.documentation": "https://github.com/netbox-community/netbox-docker/wiki",
  "org.opencontainers.image.licenses": "Apache-2.0",
  "org.opencontainers.image.revision": "c80fb19507679938528817ab8a9b03514bd1e8be",
  "org.opencontainers.image.source": "https://github.com/netbox-community/netbox-docker.git",
  "org.opencontainers.image.title": "NetBox Docker",
  "org.opencontainers.image.url": "https://github.com/netbox-community/netbox-docker",
  "org.opencontainers.image.vendor": "The netbox-docker contributors.",
  "org.opencontainers.image.version": "1.0.2"
}
```

The output of `docker-compose logs netbox`:

```text
Attaching to netbox-docker_netbox_1
netbox_1         | 🧬 loaded config '/etc/netbox/config/configuration.py'
netbox_1         | 🧬 loaded config '/etc/netbox/config/configuration.py'
netbox_1         | 🧬 loaded config '/etc/netbox/config/extra.py'
netbox_1         | 🧬 loaded config '/etc/netbox/config/logging.py'
netbox_1         | 🧬 loaded config '/etc/netbox/config/plugins.py'
netbox_1         | Operations to perform:
netbox_1         |   Apply all migrations: admin, auth, circuits, contenttypes, dcim, extras, ipam, secrets, sessions, taggit, tenancy, users, virtualization
netbox_1         | Running migrations:
netbox_1         |   No migrations to apply.
netbox_1         | 🧬 loaded config '/etc/netbox/config/configuration.py'
netbox_1         | 🧬 loaded config '/etc/netbox/config/configuration.py'
netbox_1         | 🧬 loaded config '/etc/netbox/config/extra.py'
netbox_1         | 🧬 loaded config '/etc/netbox/config/logging.py'
netbox_1         | 🧬 loaded config '/etc/netbox/config/plugins.py'
netbox_1         | 💡 Superuser Username: admin, E-Mail: admin@example.com
netbox_1         | 🧬 loaded config '/etc/netbox/config/configuration.py'
netbox_1         | 🧬 loaded config '/etc/netbox/config/configuration.py'
netbox_1         | 🧬 loaded config '/etc/netbox/config/extra.py'
netbox_1         | 🧬 loaded config '/etc/netbox/config/logging.py'
netbox_1         | 🧬 loaded config '/etc/netbox/config/plugins.py'
netbox_1         | ▶️  Running the startup script /opt/netbox/startup_scripts/000_users.py
netbox_1         | ▶️  Running the startup script /opt/netbox/startup_scripts/010_groups.py
netbox_1         | ▶️  Running the startup script /opt/netbox/startup_scripts/015_object_permissions.py
netbox_1         | ▶️  Running the startup script /opt/netbox/startup_scripts/020_custom_fields.py
netbox_1         | ▶️  Running the startup script /opt/netbox/startup_scripts/020_tags.py
netbox_1         | ▶️  Running the startup script /opt/netbox/startup_scripts/030_regions.py
netbox_1         | ▶️  Running the startup script /opt/netbox/startup_scripts/040_sites.py
netbox_1         | ▶️  Running the startup script /opt/netbox/startup_scripts/050_manufacturers.py
netbox_1         | ▶️  Running the startup script /opt/netbox/startup_scripts/060_device_types.py
netbox_1         | ▶️  Running the startup script /opt/netbox/startup_scripts/070_rack_roles.py
netbox_1         | ▶️  Running the startup script /opt/netbox/startup_scripts/075_locations.py
netbox_1         | Traceback (most recent call last):
netbox_1         |   File "./manage.py", line 10, in <module>
netbox_1         |     execute_from_command_line(sys.argv)
netbox_1         |   File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
netbox_1         |     utility.execute()
netbox_1         |   File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
netbox_1         |     self.fetch_command(subcommand).run_from_argv(self.argv)
netbox_1         |   File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
netbox_1         |     self.execute(*args, **cmd_options)
netbox_1         |   File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
netbox_1         |     output = self.handle(*args, **options)
netbox_1         |   File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/commands/shell.py", line 93, in handle
netbox_1         |     exec(sys.stdin.read())
netbox_1         |   File "<string>", line 1, in <module>
netbox_1         |   File "/usr/lib/python3.8/runpy.py", line 282, in run_path
netbox_1         |     return _run_code(code, mod_globals, init_globals,
netbox_1         |   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
netbox_1         |     exec(code, run_globals)
netbox_1         |   File "../startup_scripts/__main__.py", line 27, in <module>
netbox_1         |     runpy.run_path(f.path)
netbox_1         |   File "/usr/lib/python3.8/runpy.py", line 265, in run_path
netbox_1         |     return _run_module_code(code, init_globals, run_name,
netbox_1         |   File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
netbox_1         |     _run_code(code, mod_globals, init_globals,
netbox_1         |   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
netbox_1         |     exec(code, run_globals)
netbox_1         |   File "/opt/netbox/startup_scripts/075_locations.py", line 3, in <module>
netbox_1         |     from dcim.models import Location, Site
netbox_1         | ImportError: cannot import name 'Location' from 'dcim.models' (/opt/netbox/netbox/dcim/models/__init__.py)
```

The output of `cat docker-compose.override.yml`:

```yaml
version: '3.4'
services:
  netbox:
    ports:
      - 8000:8080
```

**Comment by cimnine** [comment]
Thank you for the detailed bug report. It realy helped to identify the (suspected) problem:

From the information you provided I can see that your _NetBox Docker files_ are [on version `1.2.0`](https://github.com/netbox-community/netbox-docker/releases/tag/1.2.0). But your _NetBox Docker image_ is `docker.io/netboxcommunity/netbox:v2.10.5`.

_NetBox Docker 1.2.0_ does only support _NetBox Docker images_ with a version of `v2.11.x`. You probably have the `v2.10.5` image in your local Docker image cache from a previous trial run. (Or, if you updated from a previous version, follow [our update instructions](https://github.com/netbox-community/netbox-docker/wiki/Updating) in the future.)

You should be able to rectify this by running `docker-compose pull` or by reverting your _NetBox Docker files_ [to version `1.1.0`](https://github.com/netbox-community/netbox-docker/releases/tag/1.1.0).

In any case, feel free to re-open the issue in the case that these instructions did rectify your problem.
