### ISSUE TITLE
Redis via Google cloud memorystore CLIENT SETNAME blocked

### ISSUE THREAD

**Issue by mumblez** [netbox-community/netbox-docker#581]
## Current Behavior

Set and export REDIS* env vars to point to google cloud memorystore redis instance

e.g.
```
REDIS_CACHE_DATABASE=0
REDIS_DATABASE=1
REDIS_SSL=false
REDIS_PORT=6379
REDIS_HOST=10.101.1.4
```

```sh
docker-compose up
Starting netbox_netbox_1 ... done
Starting netbox_netbox-worker_1 ... done
Attaching to netbox_netbox_1, netbox_netbox-worker_1
netbox-worker_1  | 🧬 loaded config '/etc/netbox/config/configuration.py'
netbox-worker_1  | 🧬 loaded config '/etc/netbox/config/extra.py'
netbox-worker_1  | 🧬 loaded config '/etc/netbox/config/logging.py'
netbox-worker_1  | 🧬 loaded config '/etc/netbox/config/plugins.py'
netbox-worker_1  | Traceback (most recent call last):
netbox-worker_1  |   File "/opt/netbox/netbox/manage.py", line 10, in <module>
netbox-worker_1  |     execute_from_command_line(sys.argv)
netbox-worker_1  |   File "/opt/netbox/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
netbox-worker_1  |     utility.execute()
netbox-worker_1  |   File "/opt/netbox/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
netbox-worker_1  |     self.fetch_command(subcommand).run_from_argv(self.argv)
netbox-worker_1  |   File "/opt/netbox/venv/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
netbox-worker_1  |     self.execute(*args, **cmd_options)
netbox-worker_1  |   File "/opt/netbox/venv/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
netbox-worker_1  |     output = self.handle(*args, **options)
netbox-worker_1  |   File "/opt/netbox/netbox/extras/management/commands/rqworker.py", line 26, in handle
netbox-worker_1  |     super().handle(*args, **options)
netbox-worker_1  |   File "/opt/netbox/venv/lib/python3.9/site-packages/django_rq/management/commands/rqworker.py", line 122, in handle
netbox-worker_1  |     w = get_worker(*args, **worker_kwargs)
netbox-worker_1  |   File "/opt/netbox/venv/lib/python3.9/site-packages/django_rq/workers.py", line 51, in get_worker
netbox-worker_1  |     return worker_class(queues,
netbox-worker_1  |   File "/opt/netbox/venv/lib/python3.9/site-packages/rq/worker.py", line 224, in __init__
netbox-worker_1  |     connection.client_setname(self.name)
netbox-worker_1  |   File "/opt/netbox/venv/lib/python3.9/site-packages/redis/client.py", line 1206, in client_setname
netbox-worker_1  |     return self.execute_command('CLIENT SETNAME', name)
netbox-worker_1  |   File "/opt/netbox/venv/lib/python3.9/site-packages/redis/client.py", line 901, in execute_command
netbox-worker_1  |     return self.parse_response(conn, command_name, **options)
netbox-worker_1  |   File "/opt/netbox/venv/lib/python3.9/site-packages/redis/client.py", line 915, in parse_response
netbox-worker_1  |     response = connection.read_response()
netbox-worker_1  |   File "/opt/netbox/venv/lib/python3.9/site-packages/redis/connection.py", line 756, in read_response
netbox-worker_1  |     raise response
netbox-worker_1  | redis.exceptions.ResponseError: unknown command `CLIENT`, with args beginning with: `SETNAME`, `41f6c8eef71443e8a7715e1906e96d99`,
netbox_1         | ⏳ Waiting on DB... (0s / 30s)
netbox_netbox-worker_1 exited with code 1
netbox_1         | ⏳ Waiting on DB... (3s / 30s)
netbox_1         | ⏳ Waiting on DB... (6s / 30s)
netbox_1         | ⏳ Waiting on DB... (9s / 30s)
netbox_1         | ⏳ Waiting on DB... (12s / 30s)
netbox_1         | ⏳ Waiting on DB... (15s / 30s)
netbox_1         | ⏳ Waiting on DB... (18s / 30s)
netbox_1         | ⏳ Waiting on DB... (21s / 30s)
netbox_1         | ⏳ Waiting on DB... (24s / 30s)
netbox_1         | ⏳ Waiting on DB... (27s / 30s)
netbox_1         | ❌ Waited 30s or more for the DB to become ready.
netbox_netbox_1 exited with code 1
```

## Expected Behavior

To successfully start netbox

## Debug Information

The output of `docker-compose version`: `3.4`
The output of `docker version`: `20.10.8`
Docker image: `netboxcommunity/netbox:v3.0.2`

For context I'm trying to scale netbox to run under a load balancer with multiple instances, I assume I need to breakout redis (hence memorystore).

**Comment by tobiasge** [comment]
The exception you see is from the Redis client. It's probably not a Docker image issue. Looks more like a compatibility problem between the client and the Google Redis implementation.
Netbox is using [django-redis](https://github.com/jazzband/django-redis) which in turn depends on [redis](https://github.com/andymccurdy/redis-py). I think you will have to open an issue there to see if this library works with Google Redis servers.
