### ISSUE TITLE
build fails: No module named 'six'

### ISSUE THREAD

**Issue by swoga** [netbox-community/netbox-docker#793]
build fails with:

```
  #12 34.38   × python setup.py egg_info did not run successfully.
  #12 34.38   │ exit code: 1
  #12 34.38   ╰─> [10 lines of output]
  #12 34.38       Traceback (most recent call last):
  #12 34.38         File "<string>", line 2, in <module>
  #12 34.38         File "<pip-setuptools-caller>", line 34, in <module>
  #12 34.38         File "/tmp/pip-install-w78n0hoc/textfsm_a55b0ce82daf4347863679ca33d0fa94/setup.py", line 20, in <module>
  #12 34.38           import textfsm
  #12 34.38         File "/tmp/pip-install-w78n0hoc/textfsm_a55b0ce82daf4347863679ca33d0fa94/textfsm/__init__.py", line 11, in <module>
  #12 34.38           from textfsm.parser import *
  #12 34.38         File "/tmp/pip-install-w78n0hoc/textfsm_a55b0ce82daf4347863679ca33d0fa94/textfsm/parser.py", line 41, in <module>
  #12 34.38           import six
  #12 34.38       ModuleNotFoundError: No module named 'six'
  #12 34.38       [end of output]
```

This is caused by `textfsm` version 1.1.3, released on Jul 6, 2022 -> https://github.com/google/textfsm/issues/105
I fixed the problem by modifying the Dockerfile and installing `six` explicitly:
```
--- a/Dockerfile
+++ b/Dockerfile
@@ -24,6 +24,7 @@ RUN apk add --no-cache \
   && /opt/netbox/venv/bin/python3 -m pip install --upgrade \
       pip \
       setuptools \
+      six \
       wheel
````

**Comment by tobiasge** [comment]
The `textfsm` dependency is pulled in from `napalm`. They fixed their dependency to `textfsm<=1.1.2` in the 4.0 release.
The update to this release is already on our `develop` branch.
